spring:
  datasource:
    url: jdbc:mariadb://cksdnr3.copcuqznwr1q.ap-northeast-2.rds.amazonaws.com:3306/cksdnr3
    driver-class-name: org.mariadb.jdbc.Driver
    username: cksdnr3
    password: duddls!2
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update